import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hotel Booking Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar />
        <nav className="flex justify-center space-x-8 bg-gray-800 py-4">
          <Link href="/" className="text-white hover:font-bold text-xl">Home</Link>
          <Link href="/about" className="text-white hover:font-bold text-xl">About</Link>
          <Link href="/hotels" className="text-white hover:font-bold text-xl">Hotels</Link>
          <Link href="/experiences" className="text-white hover:font-bold text-xl">Experiences</Link>
          <Link href="/login" className="text-white hover:font-bold text-xl">Login</Link>
        </nav>

        {children}
         <Footer />
      </body>
    </html>
  );
}
